/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentationSidebar: [
    // { type: "autogenerated", dirName: "." },
    "intro",
    {
      type: "category",
      label: "Architecture",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "Architecture/intro" },
      items: [],
    },
    {
      type: "category",
      className: "sidebar-hr",
      label: "Infrastructure",
      collapsible: false,
      collapsed: false,
      link: { type: "doc", id: "overview" },
      items: [
        "Architecture/services",
        {
          type: "category",
          label: "Getting Started",
          collapsible: true,
          collapsed: true,
          link: { type: "doc", id: "Getting-started/installation" },
          items: [],
        },
        {
          type: "category",
          label: "Tooling",
          collapsible: true,
          collapsed: true,
          items: ["Tooling/nodeRED", "Tooling/bluejay", "Tooling/openAI"],
        },
      ],
    },
    {
      type: "category",
      label: "Features",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "Features/intro" },
      items: [
        "Features/compliance-management",
        "Features/authentication",
        "Features/integrations",
        "Features/data-management",
        "Features/calculation-engine",
      ],
    },
    {
      type: "category",
      label: "STATUS API",
      collapsible: true,
      collapsed: true,
      items: [
        "Status-api/node-red",
        {
          type: "category",
          label: "Backend",
          collapsible: true,
          collapsed: true,
          link: { type: "doc", id: "Status-api/backend" },
          items: [
            "Status-api/authentication-endpoints",
            "Status-api/compliance-apis",
            "Status-api/data-integration-apis",
            "Status-api/ai-assistant-apis",
            "Status-api/system-config-apis",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Contributing",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "Contributing/guide" },
      items: [],
    },
    {
      type: "category",
      label: "Troubleshooting",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "Troubleshooting/common-issues" },
      items: [],
    },
    {
      type: "category",
      className: "sidebar-hr",
      label: "About",
      collapsible: false,
      collapsed: false,
      items: ["About/License"],
    },
  ],
};

export default sidebars;
