/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentationSidebar: [
    // { type: "autogenerated", dirName: "." },
    "Intro",
    "Overview",
    {
      type: "category",
      label: "Architecture",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "Architecture/intro" },
      items: ["Architecture/3.1.SystemPerformance"],
    },
    {
      type: "category",
      className: "sidebar-hr",
      label: "⛏️ DEVELOPMENT",
      collapsible: false,
      collapsed: false,
      items: [
        "About/6.1.License",
        {
          type: "category",
          label: "Tooling",
          collapsible: true,
          collapsed: true,
          items: ["About/6.1.License"],
        },
      ],
    },
    {
      type: "category",
      className: "sidebar-hr",
      label: "📖 ABOUT",
      collapsible: false,
      collapsed: false,
      items: ["About/6.1.License"],
    },
  ],
};

export default sidebars;
